server:
  port: 8888
  
spring:
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/SeanDiFusco/project-config.git
          username: SeanDiFusco
          password: Abb3yS1de02
          search-paths: shoppingcartservice
        encrypt:
          enabled: false